

services:
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "3000:80"
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # prevent overwriting node_modules
    environment:
      - VITE_HOST=0.0.0.0
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://gameuser:gamepass@db:5432/gamedb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: gamedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "5433:5432"


volumes:
  pgdata:
